<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 40px; color: #222; }
        .header { text-align: center; border-bottom: 3px solid #1a3d7c; padding-bottom: 15px; margin-bottom: 25px; }
        .header h1 { margin: 0; font-size: 20px; color: #1a3d7c; }
        .header p { margin: 4px 0 0; font-size: 12px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table td { padding: 6px 8px; font-size: 13px; border-bottom: 1px solid #eee; }
        table td.label { width: 200px; font-weight: bold; color: #444; }
        .status { display: inline-block; padding: 4px 12px; font-weight: bold; border-radius: 4px; }
        .status.fit { background: #d4edda; color: #155724; }
        .status.unfit { background: #f8d7da; color: #721c24; }
        .status.requires_review { background: #fff3cd; color: #856404; }
        .footer { margin-top: 40px; font-size: 11px; color: #777; border-top: 1px solid #ccc; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Foreign Employment Medical Examination Certificate</h1>
        <p>Certificate No. CERT-{{ str_pad($certificate->id, 6, '0', STR_PAD_LEFT) }}</p>
    </div>

    <table>
        <tr><td class="label">Patient Name</td><td>{{ $certificate->patient->full_name }}</td></tr>
        <tr><td class="label">Passport Number</td><td>{{ $certificate->patient->passport_number }}</td></tr>
        <tr><td class="label">Destination Country</td><td>{{ $certificate->patient->destination_country }}</td></tr>
        <tr><td class="label">Reviewing Doctor</td><td>{{ $certificate->doctor->name ?? 'N/A' }}</td></tr>
        <tr><td class="label">Issue Date</td><td>{{ optional($certificate->issue_date)->format('Y-m-d') ?? now()->format('Y-m-d') }}</td></tr>
        <tr><td class="label">Expiry Date</td><td>{{ optional($certificate->expiry_date)->format('Y-m-d') ?? 'N/A' }}</td></tr>
        <tr>
            <td class="label">Status</td>
            <td><span class="status {{ $certificate->status }}">{{ strtoupper($certificate->status) }}</span></td>
        </tr>
    </table>

    <div class="footer">
        Generated by FEMEMS on {{ now()->format('Y-m-d H:i') }}. This is a system-generated document.
    </div>
</body>
</html>
